version: '3.8'

services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:80"  # Changed port mapping
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.22
    
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: faculty_recruitment
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    ports:
      - "3306:3306"

  apache:
    image: httpd:2.4
    ports:
      - "8889:80"
    volumes:
      - ./src:/usr/local/apache2/htdocs
    depends_on:
      - php
