version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    container_name: mysql-db-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "iitpatna"
      MYSQL_DATABASE: "faculty-panel"
    volumes:
      - mysqldb_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - internalnetwork

  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache-container
    restart: unless-stopped
    ports:
      - "8000:80"
    depends_on:
      - mysqldb
    environment:
      DB_HOST: "mysqldb"
      DB_PORT: 3306
      DB_USER: "root"
      DB_PASSWORD: "iitpatna"
      DB_NAME: "faculty-panel"
    networks:
      - internalnetwork

networks:
  internalnetwork:
    driver: bridge

volumes:
  mysqldb_data: